version: '3.8'

services:
  looney-workspace:
    build: .
    container_name: looney-workspace
    ports:
      - "8080:80"
    restart: unless-stopped
    environment:
      - TZ=America/New_York
    labels:
      - "com.docker.compose.project=looney-workspace"
      - "description=Looney Tunes Workspace"
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s

networks:
  default:
    name: looney-network